### PR TITLE
Release PR - 1.2

### PR DESCRIPTION
**Pull request by ukd1**
We're adding a staging version, which is private to Rainforest for testing only. Testers should keep using the normal Chrome Store version.

This release brings:

- [x] staging, which means we can better test things before release (by @ukd1)
- [x] ``bouncer`` support, which is a faster API server (by @nxvl)
- [x] ability for rainforest to change the API endpoint that checks for work dynamically - which is good if we're under load (by @nxvl)
- [x] turn off the plugin after 6m idle (@helloworld111gh)

Everyone will get pushed this update sometime in the next day or so.

### CODE REVIEW

**Comment by ChrisRaven** [comment]
I believe, the "turn off the plugin after 6m" idle feature is really bad. There are people (like me), who use other browser as their default (e.g. Firefox), and have Chrome opened only for the tests. In such cases, the plugin will be turning off ifself very often and it will be quite annoying.
In the matter of fact, also the 10x slowing in the current version of the plugin is not very good for such users (using other browsers).
Maybe add some options to the plugin, so users will be able to set by themselves if they want to turn off the plugin after some time, or not. Other options could be ways of alerting about a new test (e.g.: sound, notification, tab flashing, etc.)

**Comment by helloworld111gh** [comment]
You are only considered idle if you do not use the mouse/keyboard after the
specified period. It shouldn't go idle if you are using a different program.

**Comment by ChrisRaven** [comment]
Oh, ok, my bad then. But still, 6 minutes sounds definitely too short. Just watch some YT or move away for a couple of minutes from the computer, and the extension will be turned off. You will have to constantly recheck, if it's turned off or not. At least, the extension should be reactivated when there's some new activity from user after a break.

**Comment by helloworld111gh** [comment]
The 6 minutes is picked out of thin air, I set it at 13 minutes when I
submitted the feature request but I reduced it. But changing the time is
very easy so I'll see what RF has to say

**Comment by ChrisRaven** [comment]
I'm not sure, if turning off the addon completely (after any period of time) is a good idea. As far, as I can tell, now, when in idle state, it checks for a test every 80 s, which seems quite a long period and shouldn't make any meaning difference, both on the RF servers and a user's computer.
Moreover, I like to just turn on my computer, run Chrome and do some other activities (not on the computer). In such situation, I would just have to edit the extension to match my needs, but there are many users, which probably don't know, how to do it, and it could be a problem for them.

**Comment by helloworld111gh** [comment]
Having an auto shut off prevents idle users from taking jobs and gives more
jobs to active workers. The time could be changed but I would put it at
most 20 min (more and many computers turn off screens or go to sleep).
Rainforest always has the final say though. @ukd1

80 seconds delay for idle is def. too long though, I would reduce it to 32
seconds with 6 min shut off timer or 60 sec with a 13+ shut off timer

**Comment by ukd1** [comment]
@helloworld111gh @ChrisRaven it really boils down to this:

> Should someone "idle" get work over someone who is not. 

I think clearly the answer is no, they shouldn't. This fixes that. If it's damaging, we'll increase and or revert it.

**Comment by ChrisRaven** [comment]
The answer is "yes, they should". It shouldn't be of any interest to RF, what somebody's doing, when he's not doing the tests. If he's actively using his computer in that time or not is only his will.
Also the "idle" state is quite problematic, because when somebody's doing something on the computer, it could also change its state to "idle". Such thing can happen during watching a movie, or during reading some longer texts. Also, often using mouse scroll isn't taken as activity, so one may read something, scroll the text, but computer still will be in the idle state.
Moreover, some people like to turn on the computer, and doing something near it not using it for a time. I, for example, like to read a book waiting for a test. In such cases, the "turn off after 6min idle" feature will be a punishment for nothing (or, for reading a book, instead of clicking something).
Also, remembering to do something to not be "idle" every so often, might be quite stressful (e.g. I want to watch 10 minutes video on YT and I will have to move my mouse in the middle of it, because otherwise the plugin will turn off and will I have to remember to turn it on again). I think, the tests themselves can be quite stressful (e.g.: very slow terminal, problems with screenshots, application error, application offline for maintenance, many substeps in each step, "oops" messages, etc., etc.) and it's not necessary to add another stress factor on top of that, especially, when potential benefits would be neglible (I doubt that a single ajax call every 80 s is such a big problem).

**Comment by Foreverrr** [comment]
@ChrisRaven 

A simple way to avoid the auto shut off thing would be to put a website on auto refresh on Chrome, for example you put google.com to be refreshed every minute or every 2-3 minutes and it will prevent your Chrome to considerate you Idle, this way the extension will always remain active...

**Comment by ChrisRaven** [comment]
@Foreverrr 
That could be a solution. Unfortunately, it doesn't work. At least, it didn't work for me, when I've checked it a moment ago using some extension called Refresh Monkey. When the status has changed to "idle" it remained in that state, no matter, how many times, a website was refreshed. Only moving mouse changed the status to "active" again.

**Comment by Foreverrr** [comment]
@ChrisRaven 

Then, an Auto Clicker should solve the problem

https://www.murgee.com/auto-clicker/

You can put it to click on an selected area at what time interval you want...

I believe that this should solve it :)

**Comment by ChrisRaven** [comment]
@Foreverrr Indeed, that program should do the trick (it worked when I've tested it a couple of minutes ago). Thanks :)
But let's hope, it won't be needed to use another program just to be able to use the free time between tests on your own way.

**Comment by Foreverrr** [comment]
@ChrisRaven 

It seems that they want this, personally I don't see why, cause like you say, you may be reading and waiting for a test, or you may eat and waiting for a test, or you may do some cooking, or anything else, I really don't see the point, since there are ways to prevent the idle status of your Chrome, this is new extension rule is useless,

Also, when I'm going out or something I always turn the extension OFF in order to not receive hits that I will lose, cause those hits affect Rainforest Accuracy...

**Comment by ChrisRaven** [comment]
@Foreverrr Exactly. When I'm going to do some tests, I'm turning the extension on and this usually means, that I'm ready to do test the moment it shows, even when I'm "idle". When I'm going out, I just turn off the computer.

**Pull request merged**
