### PR TITLE
update bugs (tested code)

### PR DESCRIPTION
**Pull request by sweeneyapps**
- updated bugs that I reported on Issue at https://github.com/rainforestapp/tester-chrome-extension/issues/315
   the bug already have the assignment url but dropped after chrome.runtime.error because tab is closed!  It went over again to the next run, checking job again after 16 seconds delay.   Also the workTab was not updated correctly.
- don't really need refreshTabInfo() anymore..   btw chrome.tabs.selected is Deprecated since Chrome 33.
- I documented what the code does.
- this code already passed tons of test... and it works HEAVENLY!   if worker forgot to close the tab after completing the job, no problem!, new tab solved everything.   appState.workTab is updated right away.   Old code, the appState.workTab has old tab (closed) and mess it up.

### CODE REVIEW

**Comment by sweeneyapps** [comment]
@ukd1 @pscohn @shosti   Just wanna to grab your attention on this.. so we can get this bug fixed ASAP.  and also I submit another PULL on increasing DEFAULT_INTERVAL to 20 sec.   16 sec doesn't work well w/ your server.

**Comment by JrRandy** [comment]
@sweeneyapps Does the change to 20 secs stop the "Too many requests" on every 3rd poll the extension does?  I also noticed that the extension randomly stops polling for large periods of time and then begins again.

**Comment by sweeneyapps** [comment]
@JrRandy  Yes, 20 seconds solves the problem w/ every 3rd polling request.    The extension does increase the polling interval time if you are idle from the computer.  I am going to explain how their idling policy is set at:  when the extension discovered that you re idling, they add 10 times the normal polling interval time.   The idle policy is at DEFAULT_INTERVAL * 3 / 1000 which is 48 seconds.  So if u re away from the computer for 48 seconds...  they will increase the polling interval time (10 * DEFAULT_INTERVAL / 1000 = 160 seconds) but when you return to the computer, everything will be back to normal to DEFAULT_INTERVAL time BUT... you'll have to wait until idle TIMER to expire.    There's a tip, if u don't want to wait for the idle TIMER to expire.  You can click the Rainforest icon to OFF then ON.  They will check job asap and reset back to normal DEFAULT_INTERVAL time.

**Comment by sweeneyapps** [comment]
I just found out that u guys are doing 2.0 version and not even bother to getting in touch w/ me.  so i'm closing this.

**Pull request closed without merging**
