### PR TITLE
Remove work tabs automatically

### LINKED ISSUE #535: Extension opens many tabs.
Extension opens many tabs. Until the hit has not been caught.

### PR DESCRIPTION
**Pull request by shosti**
Fixes #535

@rainforestapp/tester-product @ukd1

### CODE REVIEW

**Comment by ukd1** [comment]
@shosti should this only remove tabs if they're not in focus? What happens if this is the last tab open; will it kill the extension from running?

**Comment by shosti** [comment]
Good point about the last tab (although it would be a bit difficult for that to happen). It has to kill in-focus tabs because the plugin automatically focuses the work tab, and that's the issue originally reported. 

An alternative might be to only kill the work tab before opening a new one--seems a bit less aggressive. Think it's better?

**Comment by ukd1** [comment]
@shosti why not kill any open-rainforest tabs AFTER the new work tab is created?

**Comment by shosti** [comment]
k updated. Better?

**Pull request merged**
