### PR TITLE
Use CDN version of babel-polyfill and fetch

### PR DESCRIPTION
**Pull request by shosti**
Should make the download more manageable on our end (143k vs 300k), and
the CDN lib should be cached.

### CODE REVIEW

**Comment by shosti** [comment]
Need to test this manually...

**Comment by sweeneyapps** [comment]
work good on development side.   
image

**Comment by shosti** [comment]
OK seems to work locally. Will try it out in staging to be sure.

**Comment by curtis-rainforestqa** [comment]
lgtm, 👍 on a successful staging test

**Pull request merged**
